services:
  db:
    image: postgres:16-alpine
    container_name: mkst_postgresql
    restart: always

    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      TZ: Asia/Seoul
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    networks:
      - mkst-network

    volumes:
      - mkst_postgresql_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER_ID} -d ${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: mkst_backend
    restart: always

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ORIGIN: ${ORIGIN}
      DB_USER_ID: ${DB_USER_ID}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "${PORT}:${PORT}"

    networks:
      - mkst-network

    volumes:
      - ./public/uploads:/app/public/uploads

    depends_on:
      db:
        condition: service_healthy

networks:
  mkst-network:
    driver: bridge

volumes:
  mkst_postgresql_data:
