services:
  prisma-studio:
    build: .
    container_name: mkst_prisma_studio
    command: npx prisma studio --port 5555 --browser none
    environment:
      DATABASE_URL: "postgresql://${DB_USER_ID}:${DB_USER_PASSWORD}@db:5432/${DB_NAME}?schema=public"
    ports:
      - "127.0.0.1:5555:5555"
    networks:
      - mkst-network

networks:
  mkst-network:
    external: true
    name: mkst_backend_mkst-network
